#!/bin/bash -l

BLAST_OUTDIR_UPPMAX=/proj/naiss2023-6-65/Milena/chapter3/all_vs_all_blastp
BLAST_OUTDIR=/Users/miltr339/work/pairwise_blast_chapter_2_3
SCRIPT_DIR=/Users/miltr339/work/PhD_code/PhD_chapter2/src


### use the chapter 3 file to get the X/Y column!!!


# python3 ../../src/get_blast_BRH.py $BLAST_OUTDIR/A_obtectus_original_header_vs_B_siliquastri_original_header.blast $BLAST_OUTDIR/B_siliquastri_original_header_vs_A_obtectus_original_header.blast

# python3 $SCRIPT_DIR/get_blast_BRH.py $BLAST_OUTDIR/A_obtectus_original_header_vs_D_carinulata_original_header.blast $BLAST_OUTDIR/D_carinulata_original_header_vs_A_obtectus_original_header.blast
# python3 $SCRIPT_DIR/get_blast_BRH.py $BLAST_OUTDIR/B_siliquastri_original_header_vs_D_carinulata_original_header.blast $BLAST_OUTDIR/D_carinulata_original_header_vs_B_siliquastri_original_header.blast
# python3 $SCRIPT_DIR/get_blast_BRH.py $BLAST_OUTDIR/C_chinensis_original_header_vs_D_carinulata_original_header.blast $BLAST_OUTDIR/D_carinulata_original_header_vs_C_chinensis_original_header.blast
# python3 $SCRIPT_DIR/get_blast_BRH.py $BLAST_OUTDIR/C_maculatus_superscaffolded_original_header_vs_D_carinulata_original_header.blast $BLAST_OUTDIR/D_carinulata_original_header_vs_C_maculatus_superscaffolded_original_header.blast 
# python3 $SCRIPT_DIR/get_blast_BRH.py $BLAST_OUTDIR/D_sublineata_original_header_vs_D_carinulata_original_header.blast $BLAST_OUTDIR/D_carinulata_original_header_vs_D_sublineata_original_header.blast

python3 $SCRIPT_DIR/get_blast_BRH.py $BLAST_OUTDIR/T_castaneum_original_header_vs_T_freemani_original_header.blast $BLAST_OUTDIR/T_freemani_original_header_vs_T_castaneum_original_header.blast
python3 $SCRIPT_DIR/get_blast_BRH.py $BLAST_OUTDIR/C_magnifica_original_header_vs_C_septempunctata_original_header.blast $BLAST_OUTDIR/C_septempunctata_original_header_vs_C_magnifica_original_header.blast